steps:
  # Run Maven build and tests
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests=false'
    dir: 'backend/user-service'
  
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service:latest'
      - '.'
    dir: 'backend/user-service'
  
  # Push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service'
  
  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/user-service'
      - 'user-service=us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service:$BUILD_ID'
      - '--namespace=ecommerce'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecommerce-cluster'
  
  # Wait for rollout to complete
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/user-service'
      - '--namespace=ecommerce'
      - '--timeout=5m'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecommerce-cluster'
  
  # Verify deployment health
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'get'
      - 'pods'
      - '-l'
      - 'app=user-service'
      - '--namespace=ecommerce'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecommerce-cluster'

# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-repo/user-service:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for entire build
timeout: 1200s

# Substitutions (can be overridden)
substitutions:
  _SERVICE_NAME: 'user-service'
  _NAMESPACE: 'ecommerce'
